import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Inter, Cormorant,Lora } from "next/font/google";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const inter = Lora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  console.log(props, 'layout')
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        <Navbar></Navbar>
        {props.children}
        <Footer></Footer>
      </body>
    </html>
  );
}
